from django.db import models

class DimArretMobilite(models.Model):
    col_stop_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_stop_nom = models.CharField(max_length=100, null=True, blank=True)
    col_lat = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_lon = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_ville = models.CharField(max_length=100, null=True, blank=True)
    col_zone_id = models.CharField(max_length=50, null=True, blank=True)
    col_accessibilite = models.CharField(max_length=100, null=True, blank=True)
    col_opened = models.CharField(max_length=100, null=True, blank=True)
    col_station = models.CharField(max_length=100, null=True, blank=True)
    col_lignes = models.CharField(max_length=100, null=True, blank=True)
    col_trafic_journalier = models.CharField(max_length=100, null=True, blank=True)
    col_trafic_annuel = models.CharField(max_length=100, null=True, blank=True)
    col_nombre_correspondances = models.CharField(max_length=100, null=True, blank=True)
    col_zone_tarifaire = models.CharField(max_length=100, null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_date_maj = models.DateTimeField(null=True, blank=True)
    col_arret_id = models.CharField(max_length=50, null=True, blank=True)
    col_nom_arret = models.CharField(max_length=100, null=True, blank=True)
    col_type_arret = models.CharField(max_length=100, null=True, blank=True)
    col_est_accessible_pmr = models.CharField(max_length=100, null=True, blank=True)
    col_equipement_abri = models.CharField(max_length=100, null=True, blank=True)
    col_equipement_affichage_temps_reel = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_latitude = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_longitude = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_commune = models.CharField(max_length=100, null=True, blank=True)

class DimCapteurStation(models.Model):
    col_station_mesure_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_code_station = models.CharField(max_length=100, null=True, blank=True)
    col_nom_station = models.CharField(max_length=100, null=True, blank=True)
    col_zone_environnement_id = models.CharField(max_length=50, null=True, blank=True)
    col_ville = models.CharField(max_length=100, null=True, blank=True)
    col_latitude = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_longitude = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_type_station = models.CharField(max_length=100, null=True, blank=True)
    col_est_active = models.CharField(max_length=100, null=True, blank=True)
    col_equip_pm25 = models.CharField(max_length=100, null=True, blank=True)
    col_equip_pm10 = models.CharField(max_length=100, null=True, blank=True)
    col_equip_no2 = models.CharField(max_length=100, null=True, blank=True)
    col_equip_o3 = models.CharField(max_length=100, null=True, blank=True)
    col_equip_so2 = models.CharField(max_length=100, null=True, blank=True)
    col_equip_co = models.CharField(max_length=100, null=True, blank=True)
    col_equip_température = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_equip_humidité = models.CharField(max_length=100, null=True, blank=True)
    col_zone = models.CharField(max_length=100, null=True, blank=True)
    col_sensor = models.CharField(max_length=100, null=True, blank=True)
    col_pm25 = models.CharField(max_length=100, null=True, blank=True)
    col_station_metric_id = models.CharField(max_length=50, null=True, blank=True)
    col_stop_id = models.CharField(max_length=50, null=True, blank=True)
    col_zone_id = models.CharField(max_length=50, null=True, blank=True)
    col_periode_mois = models.CharField(max_length=100, null=True, blank=True)
    col_annee = models.CharField(max_length=100, null=True, blank=True)
    col_mois = models.CharField(max_length=100, null=True, blank=True)
    col_station_kwh = models.CharField(max_length=100, null=True, blank=True)
    col_dechets_kg = models.CharField(max_length=100, null=True, blank=True)
    col_status = models.CharField(max_length=100, null=True, blank=True)
    col_date_generation = models.DateTimeField(null=True, blank=True)
    col_total_stations = models.CharField(max_length=100, null=True, blank=True)
    col_types_stations = models.CharField(max_length=100, null=True, blank=True)
    col_sous_types = models.CharField(max_length=100, null=True, blank=True)
    col_villes_principales = models.CharField(max_length=100, null=True, blank=True)
    col_regions = models.CharField(max_length=100, null=True, blank=True)
    col_statuts = models.CharField(max_length=100, null=True, blank=True)
    col_accessibilite = models.CharField(max_length=100, null=True, blank=True)
    col_statistiques = models.CharField(max_length=100, null=True, blank=True)
    col_station_id = models.CharField(max_length=50, null=True, blank=True)
    col_sous_type = models.CharField(max_length=100, null=True, blank=True)
    col_adresse = models.CharField(max_length=100, null=True, blank=True)
    col_departement = models.CharField(max_length=100, null=True, blank=True)
    col_region = models.CharField(max_length=100, null=True, blank=True)
    col_capacite = models.CharField(max_length=100, null=True, blank=True)
    col_services = models.CharField(max_length=100, null=True, blank=True)
    col_date_ouverture = models.DateTimeField(null=True, blank=True)
    col_statut = models.CharField(max_length=100, null=True, blank=True)
    col_description = models.CharField(max_length=100, null=True, blank=True)
    col_polluant = models.CharField(max_length=100, null=True, blank=True)
    col_concentration_moyenne = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_concentration_min = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_concentration_max = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_indice_qualite = models.CharField(max_length=100, null=True, blank=True)
    col_nombre_stations = models.CharField(max_length=100, null=True, blank=True)
    col_date_maj = models.DateTimeField(null=True, blank=True)
    col_date = models.DateTimeField(null=True, blank=True)
    col_valeur = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_unite = models.CharField(max_length=100, null=True, blank=True)
    col_indice_atmo = models.CharField(max_length=100, null=True, blank=True)
    col_qualite_air = models.CharField(max_length=100, null=True, blank=True)
    col_capteur_id = models.CharField(max_length=50, null=True, blank=True)
    col_type_capteur = models.CharField(max_length=100, null=True, blank=True)
    col_unite_mesure = models.CharField(max_length=100, null=True, blank=True)
    col_frequence_mesure_min = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_fabricant = models.CharField(max_length=100, null=True, blank=True)
    col_date_installation = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)

class DimEvenementMobilite(models.Model):
    col_accident_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_time_id = models.CharField(max_length=50, null=True, blank=True)
    col_zone_id = models.CharField(max_length=50, null=True, blank=True)
    col_lat = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_lon = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_type = models.CharField(max_length=100, null=True, blank=True)
    col_gravite = models.CharField(max_length=100, null=True, blank=True)
    col_usager_vulnerable = models.CharField(max_length=100, null=True, blank=True)
    col_gravite_estimee = models.CharField(max_length=100, null=True, blank=True)
    col_date_enrichissement = models.DateTimeField(null=True, blank=True)
    col_evenement_id = models.CharField(max_length=50, null=True, blank=True)
    col_type_evenement = models.CharField(max_length=100, null=True, blank=True)
    col_sous_type = models.CharField(max_length=100, null=True, blank=True)
    col_date_evenement = models.DateTimeField(null=True, blank=True)
    col_heure_evenement = models.CharField(max_length=100, null=True, blank=True)
    col_lieu = models.CharField(max_length=100, null=True, blank=True)
    col_nb_blesses = models.CharField(max_length=100, null=True, blank=True)
    col_impact_trafic = models.CharField(max_length=100, null=True, blank=True)
    col_description = models.CharField(max_length=100, null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_date_generation = models.DateTimeField(null=True, blank=True)
    col_total_evenements = models.CharField(max_length=100, null=True, blank=True)
    col_periode_couverture = models.CharField(max_length=100, null=True, blank=True)
    col_types_evenements = models.CharField(max_length=100, null=True, blank=True)
    col_sous_types = models.CharField(max_length=100, null=True, blank=True)
    col_gravite_repartition = models.CharField(max_length=100, null=True, blank=True)
    col_impact_trafic_repartition = models.CharField(max_length=100, null=True, blank=True)
    col_sources = models.CharField(max_length=100, null=True, blank=True)
    col_lieux_principaux = models.CharField(max_length=100, null=True, blank=True)
    col_statistiques = models.CharField(max_length=100, null=True, blank=True)
    col_date = models.DateTimeField(null=True, blank=True)
    col_nombre_accidents = models.CharField(max_length=100, null=True, blank=True)
    col_blesses_legers = models.CharField(max_length=100, null=True, blank=True)
    col_blesses_graves = models.CharField(max_length=100, null=True, blank=True)
    col_tues = models.CharField(max_length=100, null=True, blank=True)
    col_taux_mortalite = models.CharField(max_length=100, null=True, blank=True)
    col_date_collecte = models.DateTimeField(null=True, blank=True)
    col_source_signalement = models.CharField(max_length=100, null=True, blank=True)
    col_date_maj = models.DateTimeField(null=True, blank=True)
    col_date1 = models.DateField(null=True, blank=True)

class DimLigneMobilite(models.Model):
    col_line_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_line_nom = models.CharField(max_length=100, null=True, blank=True)
    col_mode = models.CharField(max_length=100, null=True, blank=True)
    col_operateur = models.CharField(max_length=100, null=True, blank=True)
    col_couleur = models.CharField(max_length=100, null=True, blank=True)
    col_actif = models.CharField(max_length=100, null=True, blank=True)
    col_created_at = models.CharField(max_length=100, null=True, blank=True)
    col_metadata = models.CharField(max_length=100, null=True, blank=True)
    col_date_enrichissement = models.DateTimeField(null=True, blank=True)
    col_code_ligne = models.CharField(max_length=100, null=True, blank=True)
    col_nom_ligne = models.CharField(max_length=100, null=True, blank=True)
    col_type_transport = models.CharField(max_length=100, null=True, blank=True)
    col_region = models.CharField(max_length=100, null=True, blank=True)
    col_longueur_reseau_km = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_nombre_stations = models.CharField(max_length=100, null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_date_extraction = models.DateTimeField(null=True, blank=True)
    col_url_source = models.CharField(max_length=100, null=True, blank=True)
    col_departement = models.CharField(max_length=100, null=True, blank=True)
    col_capacite_passagers_heure_pointe = models.CharField(max_length=100, null=True, blank=True)
    col_vitesse_moyenne_kmh = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_frequence_heure_pointe_minutes = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_frequence_heure_creuse_minutes = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_premier_service = models.CharField(max_length=100, null=True, blank=True)
    col_dernier_service = models.CharField(max_length=100, null=True, blank=True)
    col_jours_service = models.CharField(max_length=100, null=True, blank=True)
    col_accessibilite_pmr = models.CharField(max_length=100, null=True, blank=True)
    col_wifi_disponible = models.CharField(max_length=100, null=True, blank=True)
    col_climatisation = models.CharField(max_length=100, null=True, blank=True)
    col_annee_mise_service = models.CharField(max_length=100, null=True, blank=True)
    col_derniere_renovation = models.CharField(max_length=100, null=True, blank=True)
    col_materiel_roulant = models.CharField(max_length=100, null=True, blank=True)
    col_cout_exploitation_annuel_euros = models.CharField(max_length=100, null=True, blank=True)
    col_nombre_voyageurs_annuels = models.CharField(max_length=100, null=True, blank=True)
    col_taux_frequentation = models.CharField(max_length=100, null=True, blank=True)
    col_latitude_debut = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_longitude_debut = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_latitude_fin = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_longitude_fin = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_total_lignes = models.CharField(max_length=100, null=True, blank=True)
    col_par_operateur = models.CharField(max_length=100, null=True, blank=True)
    col_par_type = models.CharField(max_length=100, null=True, blank=True)
    col_par_region = models.CharField(max_length=100, null=True, blank=True)
    col_stats_longueur = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_stats_stations = models.CharField(max_length=100, null=True, blank=True)
    col_stats_capacite = models.CharField(max_length=100, null=True, blank=True)
    col_stats_cout = models.CharField(max_length=100, null=True, blank=True)
    col_stats_voyageurs = models.CharField(max_length=100, null=True, blank=True)
    col_ligne = models.CharField(max_length=100, null=True, blank=True)
    col_station = models.CharField(max_length=100, null=True, blank=True)
    col_trafic_annuel = models.CharField(max_length=100, null=True, blank=True)
    col_ville = models.CharField(max_length=100, null=True, blank=True)
    col_date_collecte = models.DateTimeField(null=True, blank=True)
    col_longueur_km = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_frequence_moyenne_min = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_trafic_journalier = models.CharField(max_length=100, null=True, blank=True)
    col_ligne_id = models.CharField(max_length=50, null=True, blank=True)
    col_nb_arrets = models.CharField(max_length=100, null=True, blank=True)
    col_exploitant = models.CharField(max_length=100, null=True, blank=True)
    col_date_maj = models.DateTimeField(null=True, blank=True)
    col_profil_congestion = models.CharField(max_length=100, null=True, blank=True)
    col_fiabilite_horaire = models.CharField(max_length=100, null=True, blank=True)
    col_perception_securite = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)

class DimModeEnvironnement(models.Model):
    col_mode_environnement_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_code_mode = models.CharField(max_length=100, null=True, blank=True)
    col_nom_mode = models.CharField(max_length=100, null=True, blank=True)
    col_type_mode = models.CharField(max_length=100, null=True, blank=True)
    col_est_electrique = models.CharField(max_length=100, null=True, blank=True)
    col_emission_factor_co2_gkm = models.CharField(max_length=100, null=True, blank=True)
    col_type_energie = models.CharField(max_length=100, null=True, blank=True)
    col_cout_energie_eur_km = models.CharField(max_length=100, null=True, blank=True)
    col_efficacite_energetique = models.CharField(max_length=100, null=True, blank=True)
    col_annee = models.CharField(max_length=100, null=True, blank=True)
    col_pays = models.CharField(max_length=100, null=True, blank=True)
    col_type_vehicule = models.CharField(max_length=100, null=True, blank=True)
    col_pourcentage_parc = models.CharField(max_length=100, null=True, blank=True)
    col_nombre_vehicules = models.CharField(max_length=100, null=True, blank=True)
    col_emissions_co2_moyennes = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_capacite_max_vehicule = models.IntegerField(null=True, blank=True)
    col_consommation_energie_kwh_km = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_emission_no2_g_km = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_emission_pm25_g_km = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_bruit_moyen_db = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_taux_recyclable = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_cout_acquisition = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_duree_vie_ans = models.IntegerField(null=True, blank=True)
    col_est_accessible_pmr = models.IntegerField(null=True, blank=True)
    col_vitesse_theorique_max = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_date1 = models.DateField(null=True, blank=True)

class DimModeVehicule(models.Model):
    col_vehicle_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_mode = models.CharField(max_length=100, null=True, blank=True)
    col_fuel_type = models.CharField(max_length=100, null=True, blank=True)
    col_year_model = models.CharField(max_length=100, null=True, blank=True)
    col_operateur = models.CharField(max_length=100, null=True, blank=True)
    col_line_id = models.CharField(max_length=50, null=True, blank=True)
    col_capacity = models.CharField(max_length=100, null=True, blank=True)
    col_eco_label = models.CharField(max_length=100, null=True, blank=True)
    col_type_vehicule = models.CharField(max_length=100, null=True, blank=True)
    col_nombre_unites = models.CharField(max_length=100, null=True, blank=True)
    col_age_moyen_annees = models.CharField(max_length=100, null=True, blank=True)
    col_emissions_co2_g_km = models.CharField(max_length=100, null=True, blank=True)
    col_consommation_l_100km = models.CharField(max_length=100, null=True, blank=True)
    col_kilometrage_annuel_moyen = models.CharField(max_length=100, null=True, blank=True)
    col_emissions_co2_annuelles_totales_tonnes = models.CharField(max_length=100, null=True, blank=True)
    col_consommation_carburant_annuelle_millions_litres = models.CharField(max_length=100, null=True, blank=True)
    col_impact_pollution_air = models.CharField(max_length=100, null=True, blank=True)
    col_annee = models.CharField(max_length=100, null=True, blank=True)
    col_total_vehicules = models.CharField(max_length=100, null=True, blank=True)
    col_particulier_nombre = models.CharField(max_length=100, null=True, blank=True)
    col_particulier_pourcentage = models.CharField(max_length=100, null=True, blank=True)
    col_taxi_nombre = models.CharField(max_length=100, null=True, blank=True)
    col_taxi_pourcentage = models.CharField(max_length=100, null=True, blank=True)
    col_uber_nombre = models.CharField(max_length=100, null=True, blank=True)
    col_uber_pourcentage = models.CharField(max_length=100, null=True, blank=True)
    col_livraison_nombre = models.CharField(max_length=100, null=True, blank=True)
    col_livraison_pourcentage = models.CharField(max_length=100, null=True, blank=True)
    col_jour = models.CharField(max_length=100, null=True, blank=True)
    col_heure = models.CharField(max_length=100, null=True, blank=True)
    col_taux_utilisation = models.CharField(max_length=100, null=True, blank=True)
    col_kilometrage_moyen_journalier = models.CharField(max_length=100, null=True, blank=True)
    col_ville = models.CharField(max_length=100, null=True, blank=True)
    col_type_principal = models.CharField(max_length=100, null=True, blank=True)
    col_sous_type = models.CharField(max_length=100, null=True, blank=True)
    col_nombre_vehicules = models.CharField(max_length=100, null=True, blank=True)
    col_pourcentage_par_type = models.CharField(max_length=100, null=True, blank=True)
    col_carburant_principal = models.CharField(max_length=100, null=True, blank=True)
    col_norme_euro = models.CharField(max_length=100, null=True, blank=True)
    col_critair = models.CharField(max_length=100, null=True, blank=True)
    col_cout_annuel_carburant = models.CharField(max_length=100, null=True, blank=True)
    col_impact_environnemental = models.CharField(max_length=100, null=True, blank=True)
    col_nombre_vehicules_actifs = models.CharField(max_length=100, null=True, blank=True)
    col_kilometrage_total_estime = models.CharField(max_length=100, null=True, blank=True)
    col_emissions_co2_heure_kg = models.CharField(max_length=100, null=True, blank=True)
    col_consommation_carburant_l = models.CharField(max_length=100, null=True, blank=True)
    col_periode_type = models.CharField(max_length=100, null=True, blank=True)
    col_mode_mobilite_id = models.CharField(max_length=50, null=True, blank=True)
    col_code_mode = models.CharField(max_length=100, null=True, blank=True)
    col_nom_mode = models.CharField(max_length=100, null=True, blank=True)
    col_type_mode = models.CharField(max_length=100, null=True, blank=True)
    col_est_motorise = models.CharField(max_length=100, null=True, blank=True)
    col_capacite = models.CharField(max_length=100, null=True, blank=True)
    col_vitesse_max = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_vitesse_max_theorique = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_categorie_energie = models.CharField(max_length=100, null=True, blank=True)
    col_niveau_service = models.CharField(max_length=100, null=True, blank=True)
    col_cout_utilisation = models.CharField(max_length=100, null=True, blank=True)
    col_accessibilite = models.CharField(max_length=100, null=True, blank=True)
    col_infrastructure_requise = models.CharField(max_length=100, null=True, blank=True)
    col_zone_couverture = models.CharField(max_length=100, null=True, blank=True)
    col_frequence_service = models.CharField(max_length=100, null=True, blank=True)
    col_niveau_bruit = models.CharField(max_length=100, null=True, blank=True)
    col_emission_co2_km = models.CharField(max_length=100, null=True, blank=True)
    col_consommation_energie = models.CharField(max_length=100, null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_mode_id = models.CharField(max_length=50, null=True, blank=True)
    col_type_transport = models.CharField(max_length=100, null=True, blank=True)
    col_type_carburant = models.CharField(max_length=100, null=True, blank=True)
    col_emission_co2_moyenne = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_capacite_passagers = models.CharField(max_length=100, null=True, blank=True)
    col_vitesse_moyenne = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_date_maj = models.DateTimeField(null=True, blank=True)
    col_type_motorisation = models.CharField(max_length=100, null=True, blank=True)
    col_categorie_vignette = models.CharField(max_length=100, null=True, blank=True)
    col_impact_qualite_air = models.CharField(max_length=100, null=True, blank=True)
    col_dispositif_securite = models.CharField(max_length=100, null=True, blank=True)

class DimPolluant(models.Model):
    col_polluant_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_code_polluant = models.CharField(max_length=100, null=True, blank=True)
    col_nom_polluant = models.CharField(max_length=100, null=True, blank=True)
    col_unite_mesure = models.CharField(max_length=100, null=True, blank=True)
    col_seuil_alert = models.CharField(max_length=100, null=True, blank=True)
    col_seuil_critique = models.CharField(max_length=100, null=True, blank=True)
    col_source_principale = models.CharField(max_length=100, null=True, blank=True)
    col_impact_sante = models.CharField(max_length=100, null=True, blank=True)
    col_date = models.DateTimeField(null=True, blank=True)
    col_polluant = models.CharField(max_length=100, null=True, blank=True)
    col_concentration_moyenne = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_evolution_annuelle = models.CharField(max_length=100, null=True, blank=True)
    col_tendance = models.CharField(max_length=100, null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_location = models.CharField(max_length=100, null=True, blank=True)
    col_city = models.CharField(max_length=100, null=True, blank=True)
    col_country = models.IntegerField(null=True, blank=True)
    col_parameter = models.CharField(max_length=100, null=True, blank=True)
    col_value = models.CharField(max_length=100, null=True, blank=True)
    col_unit = models.CharField(max_length=100, null=True, blank=True)
    col_date_utc = models.DateTimeField(null=True, blank=True)
    col_latitude = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_longitude = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_symbole_chimique = models.CharField(max_length=100, null=True, blank=True)
    col_dangerosite = models.CharField(max_length=100, null=True, blank=True)
    col_seuil_alerte = models.CharField(max_length=100, null=True, blank=True)
    col_unite = models.CharField(max_length=100, null=True, blank=True)
    col_date_maj = models.DateTimeField(null=True, blank=True)

class DimSecurite(models.Model):
    col_securite_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_nom_zone = models.CharField(max_length=100, null=True, blank=True)
    col_ville = models.CharField(max_length=100, null=True, blank=True)
    col_niveau_securite = models.CharField(max_length=100, null=True, blank=True)
    col_nbr_cameras = models.IntegerField(null=True, blank=True)
    col_sentiment_securite = models.CharField(max_length=100, null=True, blank=True)
    col_taux_delinquance = models.CharField(max_length=100, null=True, blank=True)
    col_periodicite_patrouille = models.CharField(max_length=100, null=True, blank=True)
    col_zone_couverte_camera = models.CharField(max_length=100, null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_date_maj = models.DateTimeField(null=True, blank=True)

class DimSegmentMobilite(models.Model):
    col_segment_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_line_id = models.CharField(max_length=50, null=True, blank=True)
    col_stop_id_from = models.CharField(max_length=50, null=True, blank=True)
    col_stop_id_to = models.CharField(max_length=50, null=True, blank=True)
    col_distance_m = models.CharField(max_length=100, null=True, blank=True)
    col_temps_theorique_s = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_segment_id_line_id_stop_from = models.CharField(max_length=50, null=True, blank=True)
    col_stop_to = models.CharField(max_length=100, null=True, blank=True)
    col_dist_m_t_theo = models.CharField(max_length=100, null=True, blank=True)
    col_stop_from = models.CharField(max_length=100, null=True, blank=True)
    col_dist_m = models.CharField(max_length=100, null=True, blank=True)
    col_t_theo = models.CharField(max_length=100, null=True, blank=True)
    col_nom_rue = models.CharField(max_length=100, null=True, blank=True)
    col_type_route = models.CharField(max_length=100, null=True, blank=True)
    col_vitesse_limite = models.CharField(max_length=100, null=True, blank=True)
    col_nb_voies = models.CharField(max_length=100, null=True, blank=True)
    col_longueur_m = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_sens_unique = models.CharField(max_length=100, null=True, blank=True)
    col_date_maj = models.DateTimeField(null=True, blank=True)

class DimTime(models.Model):
    col_time_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_date = models.DateTimeField(null=True, blank=True)
    col_annee = models.CharField(max_length=100, null=True, blank=True)
    col_mois = models.CharField(max_length=100, null=True, blank=True)
    col_jour = models.CharField(max_length=100, null=True, blank=True)
    col_heure = models.CharField(max_length=100, null=True, blank=True)
    col_trimestre = models.CharField(max_length=100, null=True, blank=True)
    col_semaine = models.CharField(max_length=100, null=True, blank=True)
    col_nom_jour = models.CharField(max_length=100, null=True, blank=True)
    col_saison = models.CharField(max_length=100, null=True, blank=True)
    col_est_weekend = models.CharField(max_length=100, null=True, blank=True)
    col_creneau_horaire = models.CharField(max_length=100, null=True, blank=True)
    col_polluant = models.CharField(max_length=100, null=True, blank=True)
    col_concentration = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_unite = models.CharField(max_length=100, null=True, blank=True)
    col_station_poll = models.CharField(max_length=100, null=True, blank=True)
    col_condition_meteo = models.CharField(max_length=100, null=True, blank=True)
    col_temperature_celsius = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_ressentie_celsius = models.CharField(max_length=100, null=True, blank=True)
    col_humidite_pourcent = models.CharField(max_length=100, null=True, blank=True)
    col_pression_hpa = models.CharField(max_length=100, null=True, blank=True)
    col_vitesse_vent_kmh = models.CharField(max_length=100, null=True, blank=True)
    col_visibilite_km = models.CharField(max_length=100, null=True, blank=True)
    col_precipitations_mm = models.CharField(max_length=100, null=True, blank=True)
    col_indice_uv = models.CharField(max_length=100, null=True, blank=True)
    col_qualite_air_locale = models.CharField(max_length=100, null=True, blank=True)
    col_alerte_meteo = models.CharField(max_length=100, null=True, blank=True)
    col_nom_zone = models.CharField(max_length=100, null=True, blank=True)
    col_type_zone = models.CharField(max_length=100, null=True, blank=True)
    col_indice_pollution = models.CharField(max_length=100, null=True, blank=True)
    col_niveau_bruit_db = models.CharField(max_length=100, null=True, blank=True)
    col_biodiversite_index = models.IntegerField(null=True, blank=True)
    col_type_horaire_pointe = models.CharField(max_length=100, null=True, blank=True)

class DimTypeCarburant(models.Model):
    col_type_carburant_id = models.IntegerField(blank=True, primary_key=True)
    col_code_carburant = models.CharField(max_length=100, null=True, blank=True)
    col_nom_carburant = models.CharField(max_length=100, null=True, blank=True)
    col_type_energie = models.CharField(max_length=100, null=True, blank=True)
    col_emission_co2_litre = models.CharField(max_length=100, null=True, blank=True)
    col_part_biofuel_pct = models.CharField(max_length=100, null=True, blank=True)
    col_prix_moyen_eur_litre = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_disponibilite_nationale = models.CharField(max_length=100, null=True, blank=True)
    col_objectif_transition_2030 = models.CharField(max_length=100, null=True, blank=True)
    col_price_id = models.CharField(max_length=50, null=True, blank=True)
    col_region = models.CharField(max_length=100, null=True, blank=True)
    col_periode_mois = models.CharField(max_length=100, null=True, blank=True)
    col_annee = models.CharField(max_length=100, null=True, blank=True)
    col_mois = models.CharField(max_length=100, null=True, blank=True)
    col_fuel_type = models.CharField(max_length=100, null=True, blank=True)
    col_prix_unitaire = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_devise = models.CharField(max_length=100, null=True, blank=True)
    col_id_station = models.CharField(max_length=50, null=True, blank=True)
    col_departement = models.CharField(max_length=100, null=True, blank=True)
    col_commune = models.CharField(max_length=100, null=True, blank=True)
    col_carburant = models.CharField(max_length=100, null=True, blank=True)
    col_prix = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_date_releve = models.DateTimeField(null=True, blank=True)
    col_latitude = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_longitude = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_marque = models.CharField(max_length=100, null=True, blank=True)
    col_services = models.CharField(max_length=100, null=True, blank=True)
    col_date = models.DateTimeField(null=True, blank=True)
    col_type_carburant = models.CharField(max_length=100, null=True, blank=True)
    col_prix_moyen = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_prix_min = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_prix_max = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_evolution_annuelle_pourcent = models.CharField(max_length=100, null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_type_vehicule = models.CharField(max_length=100, null=True, blank=True)
    col_facteur_emission_co2_g_km = models.CharField(max_length=100, null=True, blank=True)
    col_facteur_emission_nox_g_km = models.CharField(max_length=100, null=True, blank=True)
    col_facteur_emission_pm_g_km = models.CharField(max_length=100, null=True, blank=True)
    col_unite = models.CharField(max_length=100, null=True, blank=True)
    col_incertitude = models.CharField(max_length=100, null=True, blank=True)
    col_date_maj = models.DateTimeField(null=True, blank=True)
    col_validite = models.CharField(max_length=100, null=True, blank=True)
    col_indice_prix_gazole = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_indice_prix_sp95 = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_indice_prix_sp98 = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_variation_mensuelle_gazole = models.CharField(max_length=100, null=True, blank=True)
    col_variation_mensuelle_sp95 = models.CharField(max_length=100, null=True, blank=True)
    col_variation_mensuelle_sp98 = models.CharField(max_length=100, null=True, blank=True)
    col_indice_inflation = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_carburant_id = models.CharField(max_length=50, null=True, blank=True)
    col_prix_reference = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_indice_pollution = models.CharField(max_length=100, null=True, blank=True)

class DimZone(models.Model):
    col_zone_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_type_zone = models.CharField(max_length=100, null=True, blank=True)
    col_type_cause = models.CharField(max_length=100, null=True, blank=True)
    col_nb_incidents = models.CharField(max_length=100, null=True, blank=True)
    col_frequence_percent = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_duree_moyenne_minutes = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_retard_moyen_minutes = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_gravite_dominante = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_date_analyse = models.DateTimeField(null=True, blank=True)
    col_dir = models.CharField(max_length=100, null=True, blank=True)
    col_route_concernee = models.CharField(max_length=100, null=True, blank=True)
    col_type_travaux = models.CharField(max_length=100, null=True, blank=True)
    col_date_debut = models.DateTimeField(null=True, blank=True)
    col_date_fin = models.DateTimeField(null=True, blank=True)
    col_duree_jours = models.CharField(max_length=100, null=True, blank=True)
    col_impact_circulation = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_voies_reduites = models.CharField(max_length=100, null=True, blank=True)
    col_longueur_chantier_km = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_ville = models.CharField(max_length=100, null=True, blank=True)
    col_departement = models.CharField(max_length=100, null=True, blank=True)
    col_region = models.CharField(max_length=100, null=True, blank=True)
    col_population = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_surface_zone_km2 = models.CharField(max_length=100, null=True, blank=True)
    col_nb_cameras_total_ville = models.CharField(max_length=100, null=True, blank=True)
    col_nb_cameras_dans_zone = models.CharField(max_length=100, null=True, blank=True)
    col_taux_couverture_camera_percent = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_surface_non_couverte_km2 = models.CharField(max_length=100, null=True, blank=True)
    col_nb_zones_sans_camera = models.CharField(max_length=100, null=True, blank=True)
    col_incidents_signales_moy_mensuel = models.CharField(max_length=100, null=True, blank=True)
    col_niveau_securite = models.CharField(max_length=100, null=True, blank=True)
    col_date_scraping = models.DateTimeField(null=True, blank=True)
    col_score_risque = models.IntegerField(null=True, blank=True)
    col_niveau_risque_global = models.CharField(max_length=100, null=True, blank=True)
    col_recommandation_securite = models.CharField(max_length=100, null=True, blank=True)
    col_latitude = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_longitude = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_nb_cameras = models.CharField(max_length=100, null=True, blank=True)
    col_densite_camera = models.CharField(max_length=100, null=True, blank=True)
    col_sentiment_insecurite_percent = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_taux_victimation_percent = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_niveau_insecurite = models.CharField(max_length=100, null=True, blank=True)
    col_nb_zones_risque_identifiees = models.CharField(max_length=50, null=True, blank=True)
    col_interventions_urgentes_moyenne_annuelle = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_nb_quartiers_sensibles = models.CharField(max_length=100, null=True, blank=True)
    col_annee = models.CharField(max_length=100, null=True, blank=True)
    col_zone_nom = models.CharField(max_length=100, null=True, blank=True)
    col_pays = models.CharField(max_length=100, null=True, blank=True)
    col_lat_centre = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_lon_centre = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_surface_km2 = models.CharField(max_length=100, null=True, blank=True)
    col_population_estimee = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_code_insee_commune = models.CharField(max_length=100, null=True, blank=True)
    col_note_admin = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_population_servie = models.IntegerField(null=True, blank=True)
    col_nb_arrets_total = models.IntegerField(null=True, blank=True)
    col_nb_stations_accessibles_pmr = models.IntegerField(null=True, blank=True)
    col_longueur_voirie_km = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_nb_zones_vegetalisees = models.IntegerField(null=True, blank=True)
    col_surface_vegetalisee_m2 = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_nb_evenements_annuels = models.IntegerField(null=True, blank=True)
    col_score_participation_citoyenne = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_date_derniere_enquete = models.DateField(null=True, blank=True)
    col_date1 = models.DateField(null=True, blank=True)

class FactEnvironnementale(models.Model):
    col_environnement_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_time_id = models.CharField(max_length=50, null=True, blank=True)
    col_zone_id = models.CharField(max_length=50, null=True, blank=True)
    col_polluant_id = models.CharField(max_length=50, null=True, blank=True)
    col_mode_id = models.CharField(max_length=50, null=True, blank=True)
    col_station_id = models.CharField(max_length=50, null=True, blank=True)
    col_valeur_co2 = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_niveau_pollution = models.CharField(max_length=100, null=True, blank=True)
    col_aqi_moyen = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_condition_meteo = models.CharField(max_length=100, null=True, blank=True)
    col_temperature = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_prix_carburant_ref = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_energie_renouvelable_pourcent = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_impact_sante_index = models.IntegerField(null=True, blank=True)
    col_cout_pollution = models.CharField(max_length=100, null=True, blank=True)
    col_energy_consumption_per_vehicle = models.CharField(max_length=100, null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_date_insertion = models.DateTimeField(null=True, blank=True)
    col_pm25 = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_no2 = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_dechets_kg = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_dechets_recycles_kg = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_taux_recyclage = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_bruit_db = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_conso_energie_totale_kwh = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_energie_renouvelable_kwh = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_surface_vegetalisee_zone = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_cout_pollution_sante = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_indice_chaleur_urbaine = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_qualite_air_globale = models.IntegerField(null=True, blank=True)
    col_date1 = models.DateField(null=True, blank=True)
    col_type_carburant_id = models.IntegerField(null=True, blank=True)
    col_price_id = models.IntegerField(null=True, blank=True)

class FactMobility(models.Model):
    col_mobilite_id = models.CharField(max_length=50, blank=True, primary_key=True)
    col_time_id = models.CharField(max_length=50, null=True, blank=True)
    col_zone_id = models.CharField(max_length=50, null=True, blank=True)
    col_mode_id = models.CharField(max_length=50, null=True, blank=True)
    col_ligne_id = models.CharField(max_length=50, null=True, blank=True)
    col_arret_id = models.CharField(max_length=50, null=True, blank=True)
    col_segment_id = models.CharField(max_length=50, null=True, blank=True)
    col_evenement_id = models.CharField(max_length=50, null=True, blank=True)
    col_vehicule_id = models.CharField(max_length=50, null=True, blank=True)
    col_trafic_mesure = models.CharField(max_length=100, null=True, blank=True)
    col_vitesse_moyenne = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_temps_attente = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_taux_frequentation = models.CharField(max_length=100, null=True, blank=True)
    col_nbr_accidents = models.IntegerField(null=True, blank=True)
    col_niveau_delinquance = models.CharField(max_length=100, null=True, blank=True)
    col_congestion_level = models.IntegerField(null=True, blank=True)
    col_est_weekend = models.CharField(max_length=100, null=True, blank=True)
    col_est_vacances = models.CharField(max_length=100, null=True, blank=True)
    col_est_jour_ferie = models.CharField(max_length=100, null=True, blank=True)
    col_is_peak_hour = models.CharField(max_length=100, null=True, blank=True)
    col_high_risk_area = models.CharField(max_length=100, null=True, blank=True)
    col_cout_energie_km = models.CharField(max_length=100, null=True, blank=True)
    col_consommation_totale = models.CharField(max_length=100, null=True, blank=True)
    col_feedback_score = models.IntegerField(null=True, blank=True)
    col_source = models.CharField(max_length=100, null=True, blank=True)
    col_date_insertion = models.DateTimeField(null=True, blank=True)
    col_heure_theorique = models.TimeField(null=True, blank=True)
    col_heure_reelle = models.TimeField(null=True, blank=True)
    col_retard_minutes = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_est_annule = models.IntegerField(null=True, blank=True)
    col_nb_passagers = models.IntegerField(null=True, blank=True)
    col_capacite_vehicule = models.IntegerField(null=True, blank=True)
    col_taux_occupation = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_distance_parcours_km = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_nb_blesses_leger = models.IntegerField(null=True, blank=True)
    col_nb_blesses_grave = models.IntegerField(null=True, blank=True)
    col_nb_tues = models.IntegerField(null=True, blank=True)
    col_nb_vulnerables_impliques = models.IntegerField(null=True, blank=True)
    col_temps_intervention_minutes = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_est_mesure_preventive = models.IntegerField(null=True, blank=True)
    col_indice_securite_percue = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_vitesse_theorique = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_temps_parcours_theorique = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_temps_parcours_reel = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_longueur_bouchon_km = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_duree_bouchon_minutes = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_cout_congestion_heure = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_nps_score = models.IntegerField(null=True, blank=True)
    col_satisfaction_score = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_stress_percu = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_nb_reclamations = models.IntegerField(null=True, blank=True)
    col_temps_reponse_reclamation_heures = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_est_fidele = models.IntegerField(null=True, blank=True)
    col_commentaire_texte = models.TextField(null=True, blank=True)
    col_sentiment_score = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_conso_energie_kwh = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_dechets_produits_kg = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_dechets_recycles_kg = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_energie_renouvelable_kwh = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_niveau_bruit_db = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_cout_operationnel = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_recettes = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_subvention_recue = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_investissement_amorti = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_economie_energie_eur = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_cout_social_evite = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_charge_predite_24h = models.IntegerField(null=True, blank=True)
    col_score_anomalie = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_impact_evenement = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_score_recommandation = models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)
    col_date1 = models.DateField(null=True, blank=True)
