/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ItineraireRouteImport } from './routes/itineraire'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as DonneesRouteImport } from './routes/donnees'
import { Route as AccessibiliteRouteImport } from './routes/accessibilite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIncidentsStreamRouteImport } from './routes/api/incidents/stream'

const ItineraireRoute = ItineraireRouteImport.update({
  id: '/itineraire',
  path: '/itineraire',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DonneesRoute = DonneesRouteImport.update({
  id: '/donnees',
  path: '/donnees',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibiliteRoute = AccessibiliteRouteImport.update({
  id: '/accessibilite',
  path: '/accessibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncidentsStreamRoute = ApiIncidentsStreamRouteImport.update({
  id: '/api/incidents/stream',
  path: '/api/incidents/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/donnees': typeof DonneesRoute
  '/incidents': typeof IncidentsRoute
  '/itineraire': typeof ItineraireRoute
  '/api/incidents/stream': typeof ApiIncidentsStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/donnees': typeof DonneesRoute
  '/incidents': typeof IncidentsRoute
  '/itineraire': typeof ItineraireRoute
  '/api/incidents/stream': typeof ApiIncidentsStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/donnees': typeof DonneesRoute
  '/incidents': typeof IncidentsRoute
  '/itineraire': typeof ItineraireRoute
  '/api/incidents/stream': typeof ApiIncidentsStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibilite'
    | '/donnees'
    | '/incidents'
    | '/itineraire'
    | '/api/incidents/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibilite'
    | '/donnees'
    | '/incidents'
    | '/itineraire'
    | '/api/incidents/stream'
  id:
    | '__root__'
    | '/'
    | '/accessibilite'
    | '/donnees'
    | '/incidents'
    | '/itineraire'
    | '/api/incidents/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibiliteRoute: typeof AccessibiliteRoute
  DonneesRoute: typeof DonneesRoute
  IncidentsRoute: typeof IncidentsRoute
  ItineraireRoute: typeof ItineraireRoute
  ApiIncidentsStreamRoute: typeof ApiIncidentsStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/itineraire': {
      id: '/itineraire'
      path: '/itineraire'
      fullPath: '/itineraire'
      preLoaderRoute: typeof ItineraireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donnees': {
      id: '/donnees'
      path: '/donnees'
      fullPath: '/donnees'
      preLoaderRoute: typeof DonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibilite': {
      id: '/accessibilite'
      path: '/accessibilite'
      fullPath: '/accessibilite'
      preLoaderRoute: typeof AccessibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incidents/stream': {
      id: '/api/incidents/stream'
      path: '/api/incidents/stream'
      fullPath: '/api/incidents/stream'
      preLoaderRoute: typeof ApiIncidentsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibiliteRoute: AccessibiliteRoute,
  DonneesRoute: DonneesRoute,
  IncidentsRoute: IncidentsRoute,
  ItineraireRoute: ItineraireRoute,
  ApiIncidentsStreamRoute: ApiIncidentsStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
