# Generated by Django 6.0.4 on 2026-04-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ministry',
            field=models.CharField(choices=[('transport', 'Transport'), ('interieur', 'Interieur'), ('amenagement', 'Amenagement du territoire'), ('transition', 'Transition ecologique')], default='transport', max_length=50),
        ),
    ]
